accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('callback/', views.Callback, name='callback'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dashboards.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

dashboards/urls.py
from django.urls import path
from dashboards import views

app_name = 'dashboards'
urlpatterns = [
    path('', views.root, name='root'),
    path('overview/', views.overview, name='overview'),
    path('time/', views.time, name='time'),
    path('tactics/', views.tactics, name='tactics'),
    path('openings/', views.openings, name='openings'),
    path('profile/', views.profile, name='profile'),
    path('fetch_games_from_api/', views.fetch_games_from_api, name='fetch_games_from_api'),
]

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from accounts.models import AuthToken
from games.services import fetch_games_from_api_service, fetch_games_from_db_service

@login_required
def root(request):
    """
    A user's session should persist as long as they are regularly using the app.
    To achieve this, request.session.modified can be set to True whenever the user
    accesses the root URL of the app, which should happen every time they launch the app.
    """
    request.session.modified = True
    return redirect('dashboards:overview')

@login_required
def overview(request):
    games = fetch_games_from_db_service(username='bbritten')
    context = {
        "user": request.user,
        "games": games,
        "num_games": len(games),
    }
    return render(request, 'dashboards/overview.html', context)

@login_required
def time(request):
    cur_time = datetime.now().isoformat()
    context = {
        "user": request.user,
        "cur_time": cur_time,
    }
    return render(request, 'dashboards/time.html', context)

@login_required
def tactics(request):
    context = {
        "user": request.user,
    }
    return render(request, 'dashboards/tactics.html', context)

@login_required
def openings(request):
    context = {
        "user": request.user,
    }
    return render(request, 'dashboards/openings.html', context)

@login_required
def profile(request):
    context = {
        "user": request.user,
    }
    return render(request, 'dashboards/profile.html', context)

@require_POST
@login_required
def fetch_games_from_api(request):
    token = request.user.authtoken.access_token
    fetch_games_from_api_service(username='bbritten', token=token)
    return redirect('dashboards:overview')

dashboards/templates/dashboards/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}
        <title>Discovered Check</title>
        {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static 'dashboards/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/fontawesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/solid.css' %}">
        <script src="{% static 'dashboards/base.js' %}"></script>
    </head>
    <body>
        <div id="main-container">
            <div id="content">
                <div id="sidebar">
                    {% include 'dashboards/sidebar.html' %}
                </div>
                <div id="canvas">
                    <div id="navbar">
                        {% include 'dashboards/navbar.html' %}
                    </div>
                    <div id="filters">
                        {% include 'dashboards/filters.html' %}
                        <button id="apply-filter-button">Apply</button>
                    </div>
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

dashboards/templates/dashboards/filters.html
<div id="filter-container">
    <div class="parameter-row">
        <div class="parameter">
            <div class="parameter-label">Date Range</div>
            <div class="parameter-content">
                <input type="date" id="start-date-parameter" name="start-date">
                <p>to</p>
                <input type="date" id="end-date-parameter" name="end-date">
            </div>
        </div>
        <div class="parameter">
            <div class="parameter-label">Color</div>
            <div class="parameter-content">
                <select id="color-parameter" name="color">
                    <option value="all">All</option>
                    <option value="white">White</option>
                    <option value="black">Black</option>
                </select>
            </div>
        </div>
        <div class="parameter">
            <div class="parameter-label">Time Class</div>
            <div class="parameter-content">
                <select id="time-class-parameter" name="time-class">
                    <option value="all">All</option>
                    <option value="bullet">Bullet</option>
                    <option value="blitz">Blitz</option>
                    <option value="rapid">Rapid</option>
                    <option value="daily">Daily</option>
                </select>
            </div>
        </div>
        <div class="parameter">
            <div class="parameter-label">Opponent ELO</div>
            <div class="parameter-content">
                <input min="0" max="3500">
                <p>to</p>
                <input min="0" max="3500">
            </div>
        </div>
        <div class="parameter">
            <div class="parameter-label">Outcome</div>
            <div class="parameter-content">
                <select id="outcome-parameter" name="outcome">
                    <option value="all">All</option>
                    <option value="win">Win</option>
                    <option value="lose">Lose</option>
                </select>
            </div>
        </div>
        <div class="spacer"></div>
    </div>
</div>

dashboards/templates/dashboards/navbar.html
<div id="navbar-container">
    <div id="user-menu">
        <div id="user-menu-container" onclick="toggleUserMenu()">
            <p id="username">{{user.username}}</p>
            <i id="username-icon" class="fa-solid fa-caret-down"></i>
        </div>
    </div>
    <div class="spacer"></div>
</div>
<div id="menu" class="hidden">
    <div class="menu-item">
        <a href="{% url 'dashboards:profile' %}">Profile</a>
    </div>
    <div class="menu-item">
        <a href="#">Submit a bug or feature request</a>
    </div>
    <div class="menu-item">
        <a href="#">View help</a>
    </div>
    <div class="menu-item">
        <a href="{% url 'accounts:logout' %}">Logout</a>
    </div>
</div>

dashboards/templates/dashboards/openings.html
{% extends 'dashboards/base.html' %}

{% block content %}
    <p>This page will eventually show analyses of openings for your games.</p>
{% endblock %}

dashboards/templates/dashboards/overview.html
{% extends 'dashboards/base.html' %}

{% block content %}
    <p>You have played {{ num_games }} games on Lichess.</p>
    <form action="{% url 'dashboards:fetch_games_from_api' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Fetch games from Lichess">
    </form>
{% endblock %}

dashboards/templates/dashboards/profile.html
{% extends 'dashboards/base.html' %}

{% block content %}
    <p>This page will eventually show your user profile including stats on games played, ELO in each time control, and more.</p>
{% endblock %}

dashboards/templates/dashboards/sidebar.html
<div id="sidebar-container">
    <div class="sidebar-card"></div>
    <a href="{% url 'dashboards:overview' %}">
        <div class="sidebar-card">
            <div class="sidebar-card-icon"><i class='fa-solid fa-chart-simple'></i></div>
            <div class="sidebar-card-label">
                <p>Overview</p>
            </div>
        </div>
    </a>
    <a href="{% url 'dashboards:openings' %}">
        <div class="sidebar-card">
            <div class="sidebar-card-icon"><i class='fa-solid fa-book'></i></div>
            <div class="sidebar-card-label">
                <p>Openings</p>
            </div>
        </div>
    </a>
    <a href="{% url 'dashboards:tactics' %}">
        <div class="sidebar-card">
            <div class="sidebar-card-icon"><i class='fa-solid fa-puzzle-piece'></i></div>
            <div class="sidebar-card-label">
                <p>Tactics</p>
            </div>
        </div>
    </a>
    <a href="{% url 'dashboards:time' %}">
        <div class="sidebar-card">
            <div class="sidebar-card-icon"><i class='fa-solid fa-clock'></i></div>
            <div class="sidebar-card-label">
                <p>Time</p>
            </div>
        </div>
    </a>
    <div class="spacer"></div>
</div>

dashboards/templates/dashboards/tactics.html
{% extends 'dashboards/base.html' %}

{% block content %}
    <p>This page will eventually show analyses of tactics for your games.</p>
{% endblock %}

dashboards/templates/dashboards/time.html
{% extends 'dashboards/base.html' %}

{% block content %}
    <p>The time is currently: {{ cur_time }}</p>
{% endblock %}